### ISSUE TITLE
building network failed with different versions of scikit-learn

### ISSUE THREAD

**Issue by berlius** [chufengxiao/Example-based-Colorization-via-Dense-Encoding-pyramids#1]
scikit-learn 0.14.1

I0620 14:15:52.286655  2457 net.cpp:746] Ignoring source layer loss8_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 50, in generate
    net.forward()
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/caffe/build/install/python/caffe/pycaffe.py", line 131, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 137, in forward
    top[0].data[...] = self.nnenc.encode_points_mtx_nd(bottom[0].data[...],axis=1)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 431, in encode_points_mtx_nd
    (dists,inds) = self.nbrs.kneighbors(pts_flt)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 313, in kneighbors
    return_distance=return_distance)
  File "binary_tree.pxi", line 1313, in sklearn.neighbors.ball_tree.BinaryTree.query (sklearn/neighbors/ball_tree.c:10036)
  File "binary_tree.pxi", line 595, in sklearn.neighbors.ball_tree.NeighborsHeap.__init__ (sklearn/neighbors/ball_tree.c:4738)
TypeError: 'float' object cannot be interpreted as an index

scikit-learn 0.15.1

I0620 14:13:42.384152  2397 net.cpp:746] Ignoring source layer loss8_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 50, in generate
    net.forward()
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/caffe/build/install/python/caffe/pycaffe.py", line 131, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 137, in forward
    top[0].data[...] = self.nnenc.encode_points_mtx_nd(bottom[0].data[...],axis=1)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 431, in encode_points_mtx_nd
    (dists,inds) = self.nbrs.kneighbors(pts_flt)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 311, in kneighbors
    return_distance=return_distance)
  File "binary_tree.pxi", line 1313, in sklearn.neighbors.ball_tree.BinaryTree.query (sklearn/neighbors/ball_tree.c:10036)
  File "binary_tree.pxi", line 595, in sklearn.neighbors.ball_tree.NeighborsHeap.__init__ (sklearn/neighbors/ball_tree.c:4738)
TypeError: 'float' object cannot be interpreted as an index

scikit-learn 0.16.1

I0620 14:18:58.575310  2780 net.cpp:746] Ignoring source layer loss8_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 50, in generate
    net.forward()
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/caffe/build/install/python/caffe/pycaffe.py", line 131, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 137, in forward
    top[0].data[...] = self.nnenc.encode_points_mtx_nd(bottom[0].data[...],axis=1)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 431, in encode_points_mtx_nd
    (dists,inds) = self.nbrs.kneighbors(pts_flt)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 374, in kneighbors
    return_distance=return_distance)
  File "binary_tree.pxi", line 1305, in sklearn.neighbors.ball_tree.BinaryTree.query (sklearn/neighbors/ball_tree.c:10578)
  File "binary_tree.pxi", line 588, in sklearn.neighbors.ball_tree.NeighborsHeap.__init__ (sklearn/neighbors/ball_tree.c:4987)
TypeError: 'float' object cannot be interpreted as an index

scikit-learn 0.17.1

I0620 14:20:38.320473  2831 net.cpp:746] Ignoring source layer loss8_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 50, in generate
    net.forward()
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/caffe/build/install/python/caffe/pycaffe.py", line 131, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 137, in forward
    top[0].data[...] = self.nnenc.encode_points_mtx_nd(bottom[0].data[...],axis=1)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 431, in encode_points_mtx_nd
    (dists,inds) = self.nbrs.kneighbors(pts_flt)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 399, in kneighbors
    for s in gen_even_slices(X.shape[0], n_jobs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "sklearn/neighbors/binary_tree.pxi", line 1310, in sklearn.neighbors.ball_tree.BinaryTree.query (sklearn/neighbors/ball_tree.c:10592)
  File "sklearn/neighbors/binary_tree.pxi", line 588, in sklearn.neighbors.ball_tree.NeighborsHeap.__init__ (sklearn/neighbors/ball_tree.c:4931)
TypeError: 'float' object cannot be interpreted as an index

scikit-learn .18.1

I0620 14:22:18.770718  2883 net.cpp:746] Ignoring source layer loss8_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 50, in generate
    net.forward()
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/caffe/build/install/python/caffe/pycaffe.py", line 131, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 137, in forward
    top[0].data[...] = self.nnenc.encode_points_mtx_nd(bottom[0].data[...],axis=1)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 431, in encode_points_mtx_nd
    (dists,inds) = self.nbrs.kneighbors(pts_flt)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 381, in kneighbors
    for s in gen_even_slices(X.shape[0], n_jobs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "sklearn/neighbors/binary_tree.pxi", line 1309, in sklearn.neighbors.ball_tree.BinaryTree.query (sklearn/neighbors/ball_tree.c:11505)
  File "sklearn/neighbors/binary_tree.pxi", line 587, in sklearn.neighbors.ball_tree.NeighborsHeap.__init__ (sklearn/neighbors/ball_tree.c:5573)
TypeError: 'float' object cannot be interpreted as an index

scikit-learn 0.19.1

I0620 14:23:44.679669  2928 net.cpp:746] Ignoring source layer loss8_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 50, in generate
    net.forward()
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/caffe/build/install/python/caffe/pycaffe.py", line 131, in _Net_forward
    self._forward(start_ind, end_ind)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 137, in forward
    top[0].data[...] = self.nnenc.encode_points_mtx_nd(bottom[0].data[...],axis=1)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 431, in encode_points_mtx_nd
    (dists,inds) = self.nbrs.kneighbors(pts_flt)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 385, in kneighbors
    for s in gen_even_slices(X.shape[0], n_jobs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "sklearn/neighbors/binary_tree.pxi", line 1309, in sklearn.neighbors.ball_tree.BinaryTree.query
  File "sklearn/neighbors/binary_tree.pxi", line 587, in sklearn.neighbors.ball_tree.NeighborsHeap.__init__
TypeError: 'float' object cannot be interpreted as an index

scikit-learn 0.20.1

I0620 14:24:56.519521  2973 net.cpp:382] refer_ab_313 -> refer_ab_313
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    generate(level)
  File "test.py", line 30, in generate
    net = caffe.Net(prototxt, model, caffe.TEST)
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 126, in setup
    self.nnenc = NNEncode(self.NN,self.sigma,km_filepath=os.path.join(self.ENC_DIR,'pts_in_hull.npy'))
  File "/content/content/Example-based-Colorization-via-Dense-Encoding-pyramids/resources/caffe_traininglayers.py", line 415, in __init__
    self.nbrs = nn.NearestNeighbors(n_neighbors=NN, algorithm='ball_tree').fit(self.cc)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 928, in fit
    return self._fit(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 276, in _fit
    type(self.n_neighbors))
TypeError: n_neighbors does not take <type 'float'> value, enter integer value

**Comment by berlius** [comment]
I was able to solve this issue by changing "NN" with "self.NN"  in your file "caffe_traininglayers.py" line 415 

before 
self.nbrs = nn.NearestNeighbors(n_neighbors=NN, algorithm='ball_tree').fit(self.cc)

after 
self.nbrs = nn.NearestNeighbors(n_neighbors=self.NN, algorithm='ball_tree').fit(self.cc)

Thanks for all your work. It's really a good neural network
