### ISSUE TITLE
Import Error : No module named caffe_traininglayers

### ISSUE THREAD

**Issue by aradhyamathur** [chufengxiao/Example-based-Colorization-via-Dense-Encoding-pyramids#4]
Upon running test.py the following error is encountered. Can you please guide what the underlying issue could be. 
```
I0826 14:34:27.938421 35394 layer_factory.hpp:77] Creating layer img_l
I0826 14:34:27.938442 35394 net.cpp:86] Creating Layer img_l
I0826 14:34:27.938449 35394 net.cpp:382] img_l -> img_l
I0826 14:34:27.938474 35394 net.cpp:124] Setting up img_l
I0826 14:34:27.938484 35394 net.cpp:131] Top shape: 1 1 64 64 (4096)
I0826 14:34:27.938489 35394 net.cpp:139] Memory required for data: 16384
I0826 14:34:27.938494 35394 layer_factory.hpp:77] Creating layer ref_ab
I0826 14:34:27.938501 35394 net.cpp:86] Creating Layer ref_ab
I0826 14:34:27.938506 35394 net.cpp:382] ref_ab -> ref_ab
I0826 14:34:27.938514 35394 net.cpp:124] Setting up ref_ab
I0826 14:34:27.938521 35394 net.cpp:131] Top shape: 1 2 64 64 (8192)
I0826 14:34:27.938526 35394 net.cpp:139] Memory required for data: 49152
I0826 14:34:27.938530 35394 layer_factory.hpp:77] Creating layer data_l_meansub
I0826 14:34:27.938539 35394 net.cpp:86] Creating Layer data_l_meansub
I0826 14:34:27.938544 35394 net.cpp:408] data_l_meansub <- img_l
I0826 14:34:27.938552 35394 net.cpp:382] data_l_meansub -> data_l
I0826 14:34:27.938568 35394 layer_factory.hpp:77] Creating layer data_l_meansub
I0826 14:34:27.938596 35394 net.cpp:124] Setting up data_l_meansub
I0826 14:34:27.938604 35394 net.cpp:131] Top shape: 1 1 64 64 (4096)
I0826 14:34:27.938609 35394 net.cpp:139] Memory required for data: 65536
I0826 14:34:27.938622 35394 layer_factory.hpp:77] Creating layer data_ab_rs
I0826 14:34:27.938630 35394 net.cpp:86] Creating Layer data_ab_rs
I0826 14:34:27.938634 35394 net.cpp:408] data_ab_rs <- ref_ab
I0826 14:34:27.938642 35394 net.cpp:382] data_ab_rs -> data_ab_rs
I0826 14:34:27.938657 35394 net.cpp:124] Setting up data_ab_rs
I0826 14:34:27.938663 35394 net.cpp:131] Top shape: 1 2 16 16 (512)
I0826 14:34:27.938668 35394 net.cpp:139] Memory required for data: 67584
I0826 14:34:27.938673 35394 layer_factory.hpp:77] Creating layer refer_ab_313
ImportError: No module named caffe_traininglayers
Traceback (most recent call last):
  File "test.py", line 113, in <module>
    generate(level)
  File "test.py", line 33, in generate
    net = caffe.Net(prototxt, model, caffe.TEST)
SystemError: NULL result without error in PyObject_Call
```

**Comment by chufengxiao** [comment]
Hi. Do you make sure you have successfully installed Caffe and Pycaffe e.g., successfully run `make runtest` at caffe directory, add the caffe files path into the environment path `PYTHONPATH` and etc.?

**Comment by aradhyamathur** [comment]
Thanks for pointing it out. There seemed to be a bug with my caffe installation. I needed to uncomment WITH_PYTHON_LAYER=1 in caffe Makefile.config. If we don't do that it may silently build while running into runtime errors.  I was able to successfully build it post this, thanks.
